url: http://baisheng.org
name: Deadline~
description: 'Love like you‘ve never been hurt,  And dance like no one‘s watching...'
pygments: true
relative_permalinks: false
permalink: /:year/:month/:day/:title/
